version: '3.8'

networks:
   neo4j-network:
    ipam:
      driver: default
      config:
        - subnet: 182.201.0.0/24

services:

  core1:
    image: neo4j:5-enterprise
    container_name: core1
    hostname: core1
    networks: 
      neo4j-network:
        ipv4_address: 182.201.0.1
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/neo4j-core1/conf:/conf
      - ./neo4j/neo4j-core1/data:/data
      - ./neo4j/neo4j-core1/logs:/logs
      - ./neo4j/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-network:5000
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_server_http_advertised_address=localhost:7474
      - NEO4j_server_colt_advertised_address=localhost:7687
      - NEO4J_AUTH=neo4j/password

  core2:
    image: neo4j:5-enterprise
    container_name: core2
    hostname: core2
    networks: 
      - neo4j-network
    ports:
      - 7475:7475
      - 7688:7688
    volumes:
      - ./neo4j/neo4j-core2/conf:/conf
      - ./neo4j/neo4j-core2/data:/data
      - ./neo4j/neo4j-core2/logs:/logs
      - ./neo4j/neo4j-core2/plugins:/plugins
    environment:
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-network:5000
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_server_http_advertised_address=localhost:7475
      - NEO4j_server_colt_advertised_address=localhost:7688
      - NEO4J_AUTH=neo4j/password

  core3:
    image: neo4j:5-enterprise
    container_name: core3
    hostname: core3
    networks: 
      - neo4j-network
    ports:
      - 7476:7475
      - 7689:7688
    volumes:
      - ./neo4j/neo4j-core3/conf:/conf
      - ./neo4j/neo4j-core3/data:/data
      - ./neo4j/neo4j-core3/logs:/logs
      - ./neo4j/neo4j-core3/plugins:/plugins
    environment:
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-network:5000
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_server_http_advertised_address=localhost:7476
      - NEO4j_server_colt_advertised_address=localhost:7689
      - NEO4J_AUTH=neo4j/password

  core4:
    image: neo4j:5-enterprise
    container_name: core4
    hostname: core4
    networks: 
      - neo4j-network
    ports:
      - 7477:7475
      - 7690:7688
    volumes:
      - ./neo4j/neo4j-core4/conf:/conf
      - ./neo4j/neo4j-core4/data:/data
      - ./neo4j/neo4j-core4/logs:/logs
      - ./neo4j/neo4j-core4/plugins:/plugins
    environment:
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-network:5000
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_server_http_advertised_address=localhost:7477
      - NEO4j_server_colt_advertised_address=localhost:7690
      - NEO4J_AUTH=neo4j/password

  jupyter:
    image: jupyter/datascience-notebook
    networks: 
      - neo4j-network
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''

