version: "3.8"

# Custom top-level network
networks:
  neo4j-internal:

services:
  # jupyter:
  #   image: jupyter/datascience-notebook
  #   networks: 
  #     - neo4j-internal
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ./:/home/jovyan/work
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   command: start-notebook.sh --NotebookApp.token=''

  server1:
    image: neo4j:4.4-enterprise
    hostname: server1
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - ./data/server1:/var/lib/neo4j/data
      - ./logs/server1:/var/lib/neo4j/logs
      - ./import:/var/lib/neo4j/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_causal__clustering_discovery__advertised__address=server1:5000
      - NEO4J_causal__clustering_transaction__advertised__address=server1:6000
      - NEO4J_causal__clustering_raft__advertised__address=server1:7000

  server2:
    image: neo4j:4.4-enterprise
    hostname: server2
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./data/server2:/var/lib/neo4j/data
      - ./logs/server2:/var/lib/neo4j/logs
      - ./import/server2:/var/lib/neo4j/import

    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password2
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_causal__clustering_discovery__advertised__address=server2:5000
      - NEO4J_causal__clustering_transaction__advertised__address=server2:6000
      - NEO4J_causal__clustering_raft__advertised__address=server2:7000
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_dbms_routing_default__router=SERVER

  server3:
    image: neo4j:4.4.21-enterprise
    hostname: server3
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - ./data/server3:/var/lib/neo4j/data
      - ./logs/server3:/var/lib/neo4j/logs
      - ./import/server3:/var/lib/neo4j/import

    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password2
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_causal__clustering_discovery__advertised__address=server3:5000
      - NEO4J_causal__clustering_transaction__advertised__address=server3:6000
      - NEO4J_causal__clustering_raft__advertised__address=server3:7000
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_dbms_routing_default__router=SERVER
